In [1]:
from matplotlib import pyplot as plt
import matplotlib.image as mpimg
%pylab inline
import pandas as pd
import numpy as np
import tensorflow as tf

Populating the interactive namespace from numpy and matplotlib


/opt/conda/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
np.set_printoptions(precision=3)
# display function
def display(alist, show = True):
    print('type:%s\nshape: %s' %(alist[0].dtype,alist[0].shape))
    if show:
        for i in range(3):
            print('example%s\n%s' %(i,alist[i]))

scalars = np.array([1,2,3],dtype=int64)
print('\nscalar')
display(scalars)

vectors = np.array([[0.1,0.1,0.1],
                   [0.2,0.2,0.2],
                   [0.3,0.3,0.3]],dtype=float32)
print('\nvector')
display(vectors)

matrices = np.array([np.array((vectors[0],vectors[0])),
                    np.array((vectors[1],vectors[1])),
                    np.array((vectors[2],vectors[2]))],dtype=float32)
print('\nmatrix')
display(matrices)


scalar
type:int64
shape: ()
example0
1
example1
2
example2
3

vector
type:float32
shape: (3,)
example0
[ 0.1  0.1  0.1]
example1
[ 0.2  0.2  0.2]
example2
[ 0.3  0.3  0.3]

matrix
type:float32
shape: (2, 3)
example0
[[ 0.1  0.1  0.1]
 [ 0.1  0.1  0.1]]
example1
[[ 0.2  0.2  0.2]
 [ 0.2  0.2  0.2]]
example2
[[ 0.3  0.3  0.3]
 [ 0.3  0.3  0.3]]


In [3]:
# input data is a list of dictionaries 
# the keys of dics are feature names, the values are feature values
examples = [{'scalar':scalars[0],
              'vector':vectors[0],
              'matrix':matrices[0]},
              {'scalar':scalars[1],
              'vector':vectors[1],
              'matrix':matrices[1]},
              {'scalar':scalars[2],
              'vector':vectors[2],
              'matrix':matrices[2]}]

In [4]:
from dataset_helper import TFrecorder

In [5]:
tfr = TFrecorder()

In [6]:
tfr.writer('testX', examples)

number of features in each example: 3
3 examples has been written to testX.tfrecord
saved data_info to testX.csv
           name     type   shape isbyte length_type default
0        scalar    int64      ()  False       fixed     NaN
1        vector  float32    (3,)  False       fixed     NaN
2        matrix  float32  (2, 3)   True       fixed     NaN
3  matrix_shape    int64    (2,)  False       fixed     NaN


In [7]:
# if run .writer(), the tfr can remember data_info and file path
dataset=tfr.get_dataset(paths=None, data_info=None, shuffle = False, batch_size = 5, epoch = 5, padding = None)

           name     type   shape isbyte length_type default
0        scalar    int64      ()  False       fixed     NaN
1        vector  float32    (3,)  False       fixed     NaN
2        matrix  float32  (2, 3)   True       fixed     NaN
3  matrix_shape    int64    (2,)  False       fixed     NaN


In [8]:
# inputing paths of tfrecord and csv files also work
dataset=tfr.get_dataset(paths='testX.tfrecord', data_info='testX.csv', shuffle = False, batch_size = 5, epoch = 5, padding = None)

read dataframe from testX.csv
           name     type   shape  isbyte length_type  default
0        scalar    int64      []   False       fixed      NaN
1        vector  float32     [3]   False       fixed      NaN
2        matrix  float32  [2, 3]    True       fixed      NaN
3  matrix_shape    int64     [2]   False       fixed      NaN


In [9]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()
sess = tf.InteractiveSession()

In [10]:
# 获得下一个样本
next_element = iterator.get_next()
# 创建Session
sess = tf.InteractiveSession()

# 获取
i = 1
while True:
    # 不断的获得下一个样本
    try:
        # 获得的值直接属于graph的一部分，所以不再需要用feed_dict来喂
        scalar,vector,matrix= sess.run([next_element['scalar'],
                                                next_element['vector'],
                                                next_element['matrix']])
    # 如果遍历完了数据集，则返回错误
    except tf.errors.OutOfRangeError:
        print("End of dataset")
        break
    else:
        # 显示每个样本中的所有feature的信息，只显示scalar的值
        print('==============example %s ==============' %i)
        print('scalar: value: %s | shape: %s | type: %s' %(scalar, scalar.shape, scalar.dtype))
        print('vector shape: %s | type: %s' %(vector.shape, vector.dtype))
        print('matrix shape: %s | type: %s' %(matrix.shape, matrix.dtype))
    i+=1

==============example 1 ==============
scalar: value: [1 2 3] | shape: (3,) | type: int64
vector shape: (3, 3) | type: float32
matrix shape: (3, 2, 3) | type: float32
==============example 2 ==============
scalar: value: [1 2 3] | shape: (3,) | type: int64
vector shape: (3, 3) | type: float32
matrix shape: (3, 2, 3) | type: float32
==============example 3 ==============
scalar: value: [1 2 3] | shape: (3,) | type: int64
vector shape: (3, 3) | type: float32
matrix shape: (3, 2, 3) | type: float32
==============example 4 ==============
scalar: value: [1 2 3] | shape: (3,) | type: int64
vector shape: (3, 3) | type: float32
matrix shape: (3, 2, 3) | type: float32
==============example 5 ==============
scalar: value: [1 2 3] | shape: (3,) | type: int64
vector shape: (3, 3) | type: float32
matrix shape: (3, 2, 3) | type: float32
End of dataset
